apiVersion: v2
type: application
version: 0.0.1
name: microservices-labs
appVersion: "0.1"
description: "Microservices Labs"

dependencies:
  - name: postgresql
    version: 12.2.7
    repository: https://charts.bitnami.com/bitnami
  - name: common
    version: 0.1.0
    repository: file://charts/common